/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.is.oop.starchy.views;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itenas.is.oop.starchy.controllers.ControllerTransaksi;
import org.itenas.is.oop.starchy.controllers.ControllerTransaksiDetail;
import java.util.List;
import java.util.ArrayList;

import java.awt.*;
import java.awt.print.*;

/**
 *
 * @Juwita
 */
public class ViewTransaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewTransaksi.class.getName());

    /**
     * Creates new form ViewTransaksi
     */
    private Connection con;
    private ControllerTransaksi ctrlTr;
    private ControllerTransaksiDetail ctrlDetail;
    private DefaultTableModel tableModel;
    
    // Variabel bantu 
    private int idTransaksiSekarang = 0; 
    private int qtyLama, idDetailTerpilih;
    private String idMenuLama;
    private boolean isModeEdit = false;
    private List<org.itenas.is.oop.starchy.models.TransaksiDetail> listBelanja = new ArrayList<>();

    public ViewTransaksi() { 
         
        initComponents();
        setLocationRelativeTo(null);

        org.itenas.is.oop.starchy.utils.ConnectorManager connMan = new org.itenas.is.oop.starchy.utils.ConnectorManager();
        this.con = connMan.connectDb(); // Di sini variabel con baru ada isinya

        this.ctrlTr = new ControllerTransaksi(this.con);
        this.ctrlDetail = new ControllerTransaksiDetail();

        this.tableModel = (DefaultTableModel) tblTransaksi.getModel();
        tableModel.setRowCount(0);
    
    }
    
    private void clearFields() {
        txtMenuID.setText("");
        txtJumlah.setText("");
        cbMetode.setSelectedIndex(0);
    }

    private void refreshTabel(String idMenu, int jumlah, int harga, String metode, int total) {
        Object[] row = {idMenu, jumlah, harga , metode, total}; 
        tableModel.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        txt1 = new javax.swing.JLabel();
        txtMenuID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        cbMetode = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btmUpdate = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        btnSimpanEdit = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI STARCHY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(338, 338, 338))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jPanel2.setForeground(new java.awt.Color(255, 153, 51));

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Menu ID", "Jumlah", "Harga Satuan", "Metode Pembayaran", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        txt1.setText("Menu ID:");

        txtMenuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuIDActionPerformed(evt);
            }
        });

        jLabel3.setText("Jumlah:");

        jLabel4.setText("Metode Pembayaran:");

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        cbMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QRIS", "CASH" }));
        cbMetode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodeActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 153, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btmUpdate.setBackground(new java.awt.Color(255, 153, 51));
        btmUpdate.setText("Ubah Pesanan");
        btmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmUpdateActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(255, 153, 51));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 153, 51));
        btnDelete.setText("Batalkan Pesanan");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 153, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSelesai.setBackground(new java.awt.Color(255, 153, 51));
        btnSelesai.setText("Selesaikan Pesanan");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnSimpanEdit.setBackground(new java.awt.Color(255, 153, 51));
        btnSimpanEdit.setText("Simpan Perubahan");
        btnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanEditActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Belanja: Rp.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSelesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnClear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNext)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSimpanEdit)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJumlah)
                                    .addComponent(txtMenuID)
                                    .addComponent(cbMetode, 0, 273, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btmUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addGap(266, 266, 266)
                                .addComponent(btnBack))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(btnNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelesai))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btmUpdate)
                        .addComponent(btnDelete)
                        .addComponent(btnSimpanEdit)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMenuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenuIDActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void cbMetodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMetodeActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil inputan
            String idMenu = txtMenuID.getText();
            int jumlahInput = Integer.parseInt(txtJumlah.getText());

            // Mencari nama menu
            String namaMenuDB = ctrlDetail.getNamaMenuByID(idMenu); 

            // Validasi stok
            boolean cukup = true;
            if (idMenu.startsWith("P")) {
                cukup = ctrlDetail.cekStokPaket(idMenu, namaMenuDB, jumlahInput);
            } else {
                cukup = ctrlDetail.getMenu_Stok(idMenu) >= jumlahInput;
            }

            if (!cukup) {
                JOptionPane.showMessageDialog(null, "Stok tidak mencukupi!");
                return; 
            }

            // Ambil harga per menu dan hitung subtotalnya
            int harga = ctrlDetail.getMenu_Harga(idMenu); 
            int subtotal = harga * jumlahInput;

            // Membungkus list belanja
            org.itenas.is.oop.starchy.models.TransaksiDetail detail = new org.itenas.is.oop.starchy.models.TransaksiDetail();

            org.itenas.is.oop.starchy.models.MenuSingle m = new org.itenas.is.oop.starchy.models.MenuSingle(0, idMenu, "", harga); 
            m.setMenu_id(idMenu);
            m.setMenu_harga(harga);
            m.setMenu_nama(namaMenuDB); 

            detail.setMenu(m);
            detail.setJumlah(jumlahInput);
            detail.setSubtotal(subtotal);

            // Masukkan ke List belanja
            listBelanja.add(detail);

            // Mengambil inputan metode
            String metodeDipilih = cbMetode.getSelectedItem().toString();

            // Menampilkan tabel
            refreshTabel(idMenu, jumlahInput, harga, metodeDipilih, subtotal); 
            
            // Metode bisa dipilih satu kali dalam 1 transaksi
            if (!listBelanja.isEmpty()) {
                cbMetode.setEnabled(false); 
            }
            
            // menghitung Total Belanja
            org.itenas.is.oop.starchy.models.Transaksi transaksiBaru = new org.itenas.is.oop.starchy.models.Transaksi();
            int totalSemua = 0;
            for (org.itenas.is.oop.starchy.models.TransaksiDetail d : listBelanja) {
                totalSemua += d.getSubtotal();
            }
            transaksiBaru.setTransaksi_total(totalSemua);
            //Memasukan total belanja ke field
            txtTotal.setText(String.valueOf(totalSemua));
            
            // Kosongkan field input
            clearFields();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Jumlah harus berupa angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed

        // TODO add your handling code here:
        try {
            // Cek apakah tabel kosong
            if (listBelanja.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Keranjang masih kosong!");
                return;
            }

            org.itenas.is.oop.starchy.models.Transaksi transaksiBaru = new org.itenas.is.oop.starchy.models.Transaksi();
            transaksiBaru.setTransaksi_date(new java.util.Date()); 

            // Simpan Metode Pembayaran dari ComboBox 
            String Metode = cbMetode.getSelectedItem().toString();
            transaksiBaru.setTransaksi_metode(org.itenas.is.oop.starchy.models.Transaksi_Metode.valueOf(Metode));

            // Menyimpan transaksi ke database
            boolean sukses = ctrlTr.create(transaksiBaru, listBelanja, org.itenas.is.oop.starchy.models.User.userLogin);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan!");

                // Menampilkan struk
                String teksStruk = Struk(cbMetode.getSelectedItem().toString());
                Object[] options = {"Cetak", "Tidak"};
                int pilih = JOptionPane.showOptionDialog(this, 
                        teksStruk, 
                        "Preview Struk", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, 
                        null, options, options[0]);

                if (pilih == 0) { //jika pilih cetak
                    cetakKePDF(teksStruk); // Panggil method di atas
                    JOptionPane.showMessageDialog(this, "Struk berhasil diproses ke PDF!");
                   
                }
                
                // Membersihkan halaman
                listBelanja.clear();
                DefaultTableModel tableModel = (DefaultTableModel) tblTransaksi.getModel();
                tableModel.setRowCount(0); 

                clearFields();
                txtTotal.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi ke database.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Selesai: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmUpdateActionPerformed
        // TODO add your handling code here:
        int baris = tblTransaksi.getSelectedRow();
        if (baris != -1) {
            // Ambil data dari baris yang dipilih
            String idMenu = tableModel.getValueAt(baris, 0).toString();
            String jumlah = tableModel.getValueAt(baris, 1).toString();
            String metode = tableModel.getValueAt(baris, 3).toString();

            txtMenuID.setText(idMenu);
            txtJumlah.setText(jumlah);
            cbMetode.setSelectedItem(metode);

            // Menyimpan data lama untuk penanda 
            this.idMenuLama = idMenu; 
            this.qtyLama = Integer.parseInt(jumlah);
            this.isModeEdit = true;
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diupdate!");
        }
    }//GEN-LAST:event_btmUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblTransaksi.getSelectedRow();
    
        if (baris != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Hapus barang dari keranjang?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                ctrlDetail.delete(listBelanja, baris);
                tableModel.removeRow(baris);

                JOptionPane.showMessageDialog(this, "Barang dihapus!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih barang yang mau dihapus dulu, Bestie!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //new ViewMenuUtama(con).setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanEditActionPerformed
        // TODO add your handling code here:
        try {
            int baris = tblTransaksi.getSelectedRow();

            if (baris != -1) {
                // Ambil semua inputan baru
                String idBaru = txtMenuID.getText();
                int qtyBaru = Integer.parseInt(txtJumlah.getText());
                String metBaru = cbMetode.getSelectedItem().toString();

                ctrlDetail.update(listBelanja, baris, idBaru, qtyBaru, metBaru);

                int hargaBaru = listBelanja.get(baris).getMenu().getMenu_harga();
                int subtotalBaru = listBelanja.get(baris).getSubtotal();
            
                // Update baris di tabel 
                tableModel.setValueAt(idBaru, baris, 0);
                tableModel.setValueAt(qtyBaru, baris, 1);
                tableModel.setValueAt(hargaBaru, baris, 2);
                tableModel.setValueAt(metBaru, baris, 3);
                tableModel.setValueAt(subtotalBaru, baris, 4);

                // Reset agar dapat input seperi biasa
                this.isModeEdit = false;
                clearFields();
                JOptionPane.showMessageDialog(this, "Berhasil mengupdate!");

            } else {
                JOptionPane.showMessageDialog(this, "Pilih barang yang ingin diupdate!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Input bermasalah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private String Struk(String metode) {
        String s = "          STARCHY FOOD & DRINK          \n";
               s += "========================================\n";
        int total = 0;
        for (org.itenas.is.oop.starchy.models.TransaksiDetail d : listBelanja) {
            String nama = d.getMenu().getMenu_nama();
            int qty = d.getJumlah();
            int sub = d.getSubtotal();
            int hrg = sub / qty;
            
            s += nama + "\n";
            s += "  " + qty + " x " + hrg + " = " + sub + "\n";
            total += sub;
        }
        s += "----------------------------------------\n";
        s += "TOTAL  : Rp " + total + "\n";
        s += "METODE : " + metode + "\n";
        s += "========================================\n";
        s += "              TERIMAKAISH                 ";
        return s;
    }
    
    private void cetakKePDF(String teks) {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable((Graphics g, PageFormat pf, int pageIndex) -> {
            if (pageIndex > 0) return Printable.NO_SUCH_PAGE;

            Graphics2D g2d = (Graphics2D) g;
            g2d.translate(pf.getImageableX(), pf.getImageableY());
            g.setFont(new Font("Monospaced", Font.PLAIN, 10)); // Font struk biar rapi

            int y = 20;
            for (String line : teks.split("\n")) {
                g.drawString(line, 10, y);
                y += 15;
            }
            return Printable.PAGE_EXISTS;
        });

        if (job.printDialog()) { // Munculin dialog print
            try { job.print(); } catch (PrinterException e) { e.printStackTrace(); }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewTransaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmUpdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnSimpanEdit;
    private javax.swing.JComboBox<String> cbMetode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JLabel txt1;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtMenuID;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
